[env]
FFMPEG_DIR = { value = "third_party/ffmpeg-8.1-dist", relative = true }
PKG_CONFIG = "C:/msys64/usr/bin/pkgconf.exe"
PKG_CONFIG_PATH = { value = "third_party/ffmpeg-8.1-dist/lib/pkgconfig", relative = true }